const char dev_cert[] = "-----BEGIN CERTIFICATE-----\n"
                        "MIIDWjCCAkKgAwIBAgIVAIqRJa57hZHNeLs/rPXIj6+kw5AjMA0GCSqGSIb3DQEB\n"
                        "CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t\n"
                        "IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMTAyMDkxNDI0\n"
                        "MDBaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh\n"
                        "dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcCddxgIBzJUeK9z6x\n"
                        "gLkDSgx7salcyCKJWRbi6HBDXoLBsE+h2xKahGY5DOcsVCZ1TwEqHWDcpfDtLw0K\n"
                        "AcCaLeJ8vpavCzYSI7InzXj9mToie0nHFlI6zJLaVLq17Im1DAq14gv7YHX2yO8U\n"
                        "N/zNUdaawsR21/4TPh3zwiU1Dmua7i/rMl/NCZc8ViuMlMGCh7hevy+OE6kTdIcB\n"
                        "GMDnA5+5KSy763tz90LChQ5SVd7y8Zpr6h76mfheiDqwwVID8+EBzdPOnKcGk1M7\n"
                        "QznuXXgL6AjjI7XCIPzUCjCLW9snTSzx5sBy/8PQkxQzdlofpmyXDfFARMz/5PbL\n"
                        "YVwzAgMBAAGjYDBeMB8GA1UdIwQYMBaAFJ/a+GEX2YJxTefTnR6ymkxEgMv6MB0G\n"
                        "A1UdDgQWBBQm+oEl55DqJORLPHqh0CznHe3eGDAMBgNVHRMBAf8EAjAAMA4GA1Ud\n"
                        "DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAmNfeN3RbGqB6Qy1wenegcvxw\n"
                        "tU+MJ5FNKg266OzgniZcwliAtNInYQAwuOKCfgcFDc2H2natGnDMB05FS+6byQIs\n"
                        "vO8pKsyk7QBpvHNYg30lTCkg24o9w5D3AgocUDdQXF8SzZm8IBZ4wsB7WazBIeYN\n"
                        "VlCZpgkDx0N/RFKmqtbrmrEqCf/qvmmxuDh/asiwwRZRoxVS2s2G3cHgLBEaSDrU\n"
                        "7F0WBBwvjr+5DQECh6Ka07OMp8genaejr1rOWvvao7JsU2UIzIrbW6ZsyOss5wB9\n"
                        "GAdVpyR3hiMo3Svlr209C42nFh3XMZaQ7Hfqs0koh6adVjXvyFOaKZoLQ+m2Hw==\n"
                        "-----END CERTIFICATE-----\n";

const unsigned dev_cert_len = sizeof(dev_cert);

const char dev_key[] = "-----BEGIN RSA PRIVATE KEY-----\n"
                       "MIIEpQIBAAKCAQEAnAnXcYCAcyVHivc+sYC5A0oMe7GpXMgiiVkW4uhwQ16CwbBP\n"
                       "odsSmoRmOQznLFQmdU8BKh1g3KXw7S8NCgHAmi3ifL6Wrws2EiOyJ814/Zk6IntJ\n"
                       "xxZSOsyS2lS6teyJtQwKteIL+2B19sjvFDf8zVHWmsLEdtf+Ez4d88IlNQ5rmu4v\n"
                       "6zJfzQmXPFYrjJTBgoe4Xr8vjhOpE3SHARjA5wOfuSksu+t7c/dCwoUOUlXe8vGa\n"
                       "a+oe+pn4Xog6sMFSA/PhAc3TzpynBpNTO0M57l14C+gI4yO1wiD81Aowi1vbJ00s\n"
                       "8ebAcv/D0JMUM3ZaH6Zslw3xQETM/+T2y2FcMwIDAQABAoIBACPtmC/IOMtKgCid\n"
                       "OVBBpVf+itVIWQjGBD2/x6dDgeXhMxZJ9Gv+N1Bgv/DO6cOpNJm6MThzP0RO6SST\n"
                       "utrdAG3/trCmaaewWyjeEz1a8ErkJyCdZqVynEhxpjajX8JXznVjamvqunuNAFxs\n"
                       "c7AiHBFikJld00LSBOyFVvwzbcHDTia1Me56ss9obeBMSFaMzbV3JwKlr+mA+wjV\n"
                       "cMTGT5EQY2HQiZXm+YK7a/GQ0x6LqPN0GefV2ReU+jtn3abflekh7EdWSRXAasWK\n"
                       "4IVvP7U+ywApRKxLMi24Tu9IMo2UTsF1hem992aZxDrOFmVberx8Hi1s/cLYudVi\n"
                       "gviiZOECgYEAzwnFGBjzxXQwCmwwy/WUTKu+C5n1AcSlTFlX3UtlmR89vaApGUtu\n"
                       "vU810VqxqQ80dGIaRQhMYmGgcXik5di4X2DWQlDFZ1JLr8bFyD4nCgCKLcozk9f6\n"
                       "DtmDklRGiys0oq89LBU8Wd1r5TRil8JAxNwgYzwFiJ88Fi/VFsxvOxkCgYEAwPCD\n"
                       "pAZIN5NkO6y4e2XrhHEv/7r45ADbb+80N4hRQyNrAwGOYzNneo97mqW8Ck6nRxce\n"
                       "BSV2Be3vAwpcX/XWlS60ngaGvLHmWYKvNWmfEZ8Q3k9XEYBKWi2NScw5AwaHtgwG\n"
                       "g4EF/d4Q0Zr2aXNzZsfVy05KE5qUQXKlxUYSxysCgYEAlv+zJe4c7Kfe2dsqg7bq\n"
                       "oDip9OAml1GKlXKb6KQyx0jHyONk1jPz4lJBGB2jcX/LbA6YxjxVKXO2hsvMyG4V\n"
                       "mkqQOfGa585XsS2x1meuJVdbcCYHFA7zK51snm6kvJ+YVgalAN/EEm6xYIuiVLiy\n"
                       "cGFzpayDBK/OLQhZy7TycxECgYEAvkQxPW7ohs32OZcR8rbGtDw+vm0vBwIFZHQ7\n"
                       "RUxL/u6NmFBPj2pg8I9QsGgicPOxqLyWYTLZGe3TF2d/Qy6XZ1TAz1nWQ30YkUr7\n"
                       "56t6L5FyvBj33w1pxVZIj+8yhdZJvPBM+CAjvX/hjCLKP6GXu1L0deKF0KFO9N/P\n"
                       "tCRvXjMCgYEAlA+W4fF2QSO9An8il3Ey0jCNxKP8c4Ysw41dE7AhhknN5DFsIDEL\n"
                       "yUOLimfQXEoUSs4iv2HUAqqtjY1WHv6WZ22v5JEBPEizIhl5/u+itK0mKzsg+oFQ\n"
                       "Od61EKQcSMx8InI7H+fC+4buKT3994mPlKhiCOh3a/nCKh1b09xRNao=\n"
                       "-----END RSA PRIVATE KEY-----\n";

const unsigned dev_key_len = sizeof(dev_key);

const char root_cert[] = "-----BEGIN CERTIFICATE-----\n"
                         "MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\n"
                         "ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\n"
                         "b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\n"
                         "MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\n"
                         "b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\n"
                         "ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\n"
                         "9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\n"
                         "IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\n"
                         "VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\n"
                         "93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\n"
                         "jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\n"
                         "AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\n"
                         "A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\n"
                         "U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\n"
                         "N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\n"
                         "o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\n"
                         "5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\n"
                         "rqXRfboQnoZsG4q5WTP468SQvvG5\n"
                         "-----END CERTIFICATE-----\n";

const unsigned root_cert_len = sizeof(root_cert);